language: go
go:
- 1.11.x

dist: xenial
sudo: required

# Force-enable Go modules. This will be unnecessary when Go 1.12 lands.
env:
- GO111MODULE=on CHANGE_MINIKUBE_NONE_USER=true INSTALL_K8S_TOOLS=1 RUN_DEP=1 IMG=kiwigrid

git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Don't email me the results of the test runs.
notifications:
  email: false

# script always runs to completion (set +e). If we have linter issues AND a
# failing test, we want to see both. Configure golangci-lint with a
# .golangci.yml file at the top level of your repo.
script:
  - sed -i s/latest/${TRAVIS_BUILD_NUMBER}/g main.go
  - docker build -t kiwigrid/pull-secret-distributor:${TRAVIS_BUILD_NUMBER} .
  - docker tag kiwigrid/pull-secret-distributor:${TRAVIS_BUILD_NUMBER} kiwigrid/pull-secret-distributor:latest
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - docker push kiwigrid/pull-secret-distributor:${TRAVIS_BUILD_NUMBER}
  - docker push kiwigrid/pull-secret-distributor:latest
